### ISSUE TITLE
test https only

### ISSUE THREAD

**Issue by Hobbit71** [opencomponents/oc-registry-test#4]
Hi,

We deliberately only serve our content over https and do not make port 80 available at all. Would you have an objection to me forking the repository and adding a command line parameter allow the tests to run over https only

So command would be `oc-registry-test https://oc.example.com --https-only`

Would put some logic into the tests to accommodate for this. Then submit back as a PR.

**Comment by matteofigus** [comment]
Sounds good! I actually think it could be ok to just remove the http test, as nowadays serving over http is anyways an anti-pattern :)

**Comment by Hobbit71** [comment]
Ok. Will make the change. Do you want me to remove http or add the parameter?

**Comment by Hobbit71** [comment]
@matteofigus all done, know you are a busy man so just let me know when you have had a look. If you want any other changes or update just shout.
